language:
  - ruby
rvm:
  - 2.5.3
sudo: true
notifications:
  slack: shakacode:YvfXbuFMcFAHt6ZjABIs0KET
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
  chrome: beta
services:
  - docker

cache:
  bundler: true
  directories:
    - node_modules # NPM packages
  yarn: true

env:
  global:
    - RAILS_ENV=test
    - DRIVER=selenium_chrome
    - CHROME_BIN=/usr/bin/google-chrome
    - USE_COVERALLS=TRUE

before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb libappindicator1 fonts-liberation
  #- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
  #- sudo dpkg -i google-chrome*.deb

install:
  - travis_retry gem install bundler -v '<2' # Ruby 2.2 and Rails 3.2 & 4.2 depend on bundler 1.x.
  - travis_retry nvm install 11.7.0
  - node -v
  - travis_retry npm i -g yarn
  - travis_retry bundle install
  - travis_retry yarn
  - bundle
  - yarn
  - node --version
  - google-chrome --version
  # Temp set chromediver to version matching chrome 73
  - chromedriver-update 73.0.3683.68
  - chromedriver --version
  - yarn install
  - rake db:setup

script:
  - bundle exec rake db:schema:load
  - bundle exec rake
