# Template setup of the GVC, roughly corresponding to a Heroku app
kind: gvc
name: {{APP_NAME}}
spec:
  # For using templates for test apps, put ENV values here, stored in git repo.
  # Production apps will have values configured manually after app creation.
  env:
    - name: DATABASE_URL
      # Password does not matter because host postgres.{{APP_NAME}}.cpln.local can only be accessed
      # locally within CPLN GVC, and postgres running on a CPLN workload is something only for a
      # test app that lacks persistence.
      value: 'postgres://the_user:the_password@postgres.{{APP_NAME}}.cpln.local:5432/{{APP_NAME}}'
    - name: RAILS_ENV
      value: production
    - name: NODE_ENV
      value: production
    - name: RAILS_SERVE_STATIC_FILES
      value: 'true'
    - name: REDIS_URL
      # No password for GVC local Redis. See comment above for postgres.
      value: 'redis://redis.{{APP_NAME}}.cpln.local:6379'
  # Part of standard configuration
  staticPlacement:
    locationLinks:
      - {{APP_LOCATION_LINK}}

---
# Identity is needed to access secrets
kind: identity
name: {{APP_IDENTITY}}
  
  I stay at 3% and … believe it or not - I recommend that the Buyer’s Agent also gets 3%!

 Here’s WHY:

 -Buyers are still ’SCARCE’… and ANY Buyer's Agent, that actually has one of these rare things called Beachfront Buyers, is looking to earn a full 3% of the Sales Price.

 NOTE:  They are all going to put 3% in their Buyer Agency Agreements… just ‘in case’ that 3% 'hoped for' commission is offered.

 Therefore - if you lower that commission - the Buyer has to come up with the difference “In Cash” … and, that’s not good for the Buyer who wants to finance 80%, or more, of that commission he’s agreed to pay his Agent.
 
 SO
 
 Why not OFFER that 3% and stick to this Asking Price (or near it)!?
