# Control Plane GitHub Action

name: Deploy to Control Plane
description: 'Deploys the application to Control Plane'

inputs:
  app_name:
    description: 'Name of the application'
    required: true
  org:
    description: 'Organization name'
    required: true
  github_token:
    description: 'GitHub token'
    required: true

outputs:
  rails_url:
    description: 'URL of the deployed Rails application'
    value: ${{ steps.deploy.outputs.rails_url }}

runs:
  using: "composite"
  steps:
    - name: Setup Environment
      uses: ./.github/actions/setup-environment

    - name: Get Commit SHA
      id: get_sha
      shell: bash
      run: |
        if [ -n "$PR_NUMBER" ]; then
          # If PR_NUMBER is set, get the PR's head SHA
          PR_SHA=$(gh pr view $PR_NUMBER --json headRefOid --jq '.headRefOid')
          echo "sha=$PR_SHA" >> $GITHUB_OUTPUT
          echo "sha_short=${PR_SHA:0:7}" >> $GITHUB_OUTPUT
          echo "Using PR head commit SHA: ${PR_SHA:0:7}"
        else
          # For direct branch deployments, use the current commit SHA
          CURRENT_SHA=$(git rev-parse HEAD)
          echo "sha=$CURRENT_SHA" >> $GITHUB_OUTPUT
          echo "sha_short=${CURRENT_SHA:0:7}" >> $GITHUB_OUTPUT
          echo "Using branch commit SHA: ${CURRENT_SHA:0:7}"
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ env.PR_NUMBER }}

    - name: Initialize Deployment
      id: init-deployment
      uses: actions/github-script@v7
      with:
        script: |
          // Create GitHub deployment
          const deployment = await github.rest.repos.createDeployment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.sha,
            environment: 'review-app',
            auto_merge: false,
            required_contexts: []
          });
          
          // Set deployment status to in_progress
          await github.rest.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: deployment.data.id,
            state: 'in_progress',
            description: 'Deployment is in progress'
          });
          
          return {
            deploymentId: deployment.data.id
          };

    - name: Build Docker Image
      id: build
      shell: bash
      run: |
        echo "🏗️ Building Docker image..."
        cpflow build-image -a ${{ inputs.app_name }} --commit=${{ github.sha }} --org=${{ inputs.org }}

    - name: Deploy to Control Plane
      id: deploy
      shell: bash
      run: |
        echo "🚀 Deploying to Control Plane..."
        TEMP_OUTPUT=$(mktemp)
        
        if cpflow deploy-image -a ${{ inputs.app_name }} --run-release-phase --org ${{ inputs.org }} --verbose | tee "$TEMP_OUTPUT"; then
          # Extract Rails URL
          RAILS_URL=$(grep -o 'https://rails-[^[:space:]]*\.cpln\.app' "$TEMP_OUTPUT")
          if [ -n "$RAILS_URL" ]; then
            echo "rails_url=$RAILS_URL" >> $GITHUB_OUTPUT
            echo "✅ Deployment successful: $RAILS_URL"
          else
            echo "❌ Failed to extract Rails URL"
            exit 1
          fi
        else
          echo "❌ Deployment failed"
          exit 1
        fi
        rm -f "$TEMP_OUTPUT"
