# Control Plane GitHub Action

name: Deploy-To-Control-Plane
description: 'Deploys both to staging and to review apps'

inputs:
  app_name:
    description: 'The name of the app to deploy'
    required: true
    default:
  org:
    description: 'The org of the app to deploy'
    required: true
    default:

runs:
  using: 'composite'
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'  # Specify your Ruby version here

    - name: Install Control Plane CLI
      shell: bash
      run: |
        sudo npm install -g @controlplane/cli
        cpln --version
        gem install cpl 
        cpl --version
    - name: Set Short SHA
      id: vars
      shell: bash
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: cpl profile
      shell: bash
      run: |
        cpln profile update default

    # Caching step
    - uses: actions/cache@v2
      with:
        path: /tmp/.docker-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile', '**/package.json', '**/yarn.lock') }}-${{ github.sha   }}
        restore-keys: |
          ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile', '**/package.json', '**/yarn.lock') }}
          ${{ runner.os }}-docker-

    - name: cpl setup-app
      shell: bash
      run: |
        if ! cpl exists -a ${{ inputs.app_name }} ; then
          cpl setup-app -a ${{ inputs.app_name }}
        fi
    # Provision all infrastructure on Control Plane.
    # app react-webpack-rails-tutorial will be created per definition in .controlplane/controlplane.yml
    - name: cpl build-image
      shell: bash
      run: |
        cpln image docker-login
        BUILDKIT_PROGRESS=plain cpl build-image -a ${{ inputs.app_name }} --commit ${{steps.vars.outputs.sha_short}} --org ${{inputs.org}}
        # --cache /tmp/.docker-cache
    - name: Deploy to Control Plane
      shell: bash
      run: |
        cpl deploy-image -a ${{ inputs.app_name }} --run-release-phase --org ${{inputs.org}}  
