# Control Plane GitHub Action

name: Deploy-To-Control-Plane
description: 'Deploys both to staging and to review apps'

inputs:
  app_name:
    description: 'The name of the app to deploy'
    required: true
  org:
    description: 'The org of the app to deploy'
    required: true
  github_token:
    description: 'The GitHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Environment
      uses: ./.github/actions/setup-environment

    - name: Get correct commit SHA
      id: get_sha
      shell: bash
      run: |
        if [[ "$GITHUB_EVENT_NAME" == "issue_comment" ]]; then
          PR_SHA=$(gh pr view ${{ env.PR_NUMBER }} --json headRefOid --jq '.headRefOid')
          echo "sha=$PR_SHA" >> $GITHUB_OUTPUT
          echo "sha_short=${PR_SHA:0:7}" >> $GITHUB_OUTPUT
        else
          echo "sha=$GITHUB_SHA" >> $GITHUB_OUTPUT
          echo "sha_short=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ env.PR_NUMBER }}

    # Updated caching step to v3
    - uses: actions/cache@v3
      with:
        path: /tmp/.docker-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile', '**/package.json', '**/yarn.lock') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile', '**/package.json', '**/yarn.lock') }}
          ${{ runner.os }}-docker-

    - name: cpflow setup-app
      shell: bash
      run: |
        if ! cpflow exists -a ${{ inputs.app_name }} ; then
          cpflow setup-app -a ${{ inputs.app_name }}
        fi

    # Provision all infrastructure on Control Plane.
    # app react-webpack-rails-tutorial will be created per definition in .controlplane/controlplane.yml
    - name: Build and deploy
      shell: bash
      run: |
        cpln image docker-login
        # Use BUILDKIT_PROGRESS=plain to get more verbose logging of the build
        # BUILDKIT_PROGRESS=plain cpflow build-image -a ${{ inputs.app_name }} --commit ${{steps.get_sha.outputs.sha_short}} --org ${{inputs.org}}
        cpflow build-image -a ${{ inputs.app_name }} --commit=${{steps.get_sha.outputs.sha_short}} --org=${{inputs.org}}

    - name: Deploy to Control Plane
      shell: bash
      run: |
        echo "Deploying to Control Plane"
        cpflow deploy-image -a ${{ inputs.app_name }} --run-release-phase --org ${{inputs.org}} --verbose
