# Control Plane GitHub Action

name: Deploy to Control Plane
description: 'Deploys the application to Control Plane'

inputs:
  app_name:
    description: 'Name of the application'
    required: true
  org:
    description: 'Organization name'
    required: true
  github_token:
    description: 'GitHub token'
    required: true

outputs:
  rails_url:
    description: 'URL of the deployed Rails application'
    value: ${{ steps.deploy.outputs.rails_url }}

runs:
  using: "composite"
  steps:
    - name: Setup Environment
      uses: ./.github/actions/setup-environment

    - name: Get Commit SHA
      id: get_sha
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/scripts/get-commit-sha.sh
        ${{ github.action_path }}/scripts/get-commit-sha.sh
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ env.PR_NUMBER }}

    - name: Build Docker Image
      uses: ./.github/actions/build-docker-image
      with:
        app_name: ${{ inputs.app_name }}
        org: ${{ inputs.org }}
        commit: ${{ github.sha }}

    - name: Deploy to Control Plane
      id: deploy
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/scripts/deploy.sh
        ${{ github.action_path }}/scripts/deploy.sh
      env:
        APP_NAME: ${{ inputs.app_name }}
        CPLN_ORG: ${{ inputs.org }}
