# Restart webpack-dev-server if you make changes here
default: &default
  enabled: false
  host: localhost
  port: 3500

development:
  <<: *default
  enabled: true

test:
  <<: *default

production:
  <<: *default
