name: Delete Review App

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  deployments: write
  pull-requests: write
  issues: write

env:
  CPLN_ORG: ${{ secrets.CPLN_ORG_STAGING }}
  CPLN_TOKEN: ${{ secrets.CPLN_TOKEN_STAGING }}

jobs:
  Process-Delete-Command:
    if: |
      github.event_name == 'issue_comment' && 
      github.event.issue.pull_request && 
      github.event.comment.body == '/delete-review-app'
    runs-on: ubuntu-latest

    steps:
      - name: Get PR number
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.issue.number;
            core.setOutput('pr_number', prNumber);
            core.exportVariable('PR_NUMBER', prNumber);

      - name: Set App Name
        run: echo "APP_NAME=qa-react-webpack-rails-tutorial-pr-${{ env.PR_NUMBER }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Create Initial Delete Comment
        id: init-delete
        uses: actions/github-script@v7
        with:
          script: |
            const comment = await github.rest.issues.createComment({
              issue_number: process.env.PR_NUMBER,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🗑️ Starting app deletion...'
            });
            return { commentId: comment.data.id };

      - name: Delete Review App
        uses: ./.github/actions/delete-control-plane-app
        env:
          APP_NAME: ${{ env.APP_NAME }}
          CPLN_ORG: ${{ secrets.CPLN_ORG }}
          CPLN_TOKEN: ${{ secrets.CPLN_TOKEN }}

      - name: Update Delete Status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const success = '${{ job.status }}' === 'success';
            const prNumber = process.env.PR_NUMBER;
            const cpConsoleUrl = `https://console.cpln.io/org/${process.env.CPLN_ORG}/workloads/${process.env.APP_NAME}`;
            
            const message = success
              ? '✅ Review app for PR #' + prNumber + ' was successfully deleted'
              : [
                  '❌ Review app for PR #' + prNumber + ' failed to be deleted',
                  '',
                  '[View in Control Plane Console](' + cpConsoleUrl + ')'
                ].join('\n');
            
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ fromJSON(steps.init-delete.outputs.result).commentId }},
              body: message
            });
