name: Show Help for Commands

on:
  push:
    branches:
      - "**" # Trigger on all branches, including feature branches
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      issue-number:
        description: 'PR/Issue number to post the help comment to'
        required: true
        type: number

permissions:
  issues: write
  pull-requests: write

jobs:
  show-help:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request && 
       github.event.comment.body == '/help')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout

      - name: Show Help Information
        uses: shakacode/shared-actions/help-command@justin808-more-work-on-review-apps-2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.issue-number }}
