name: Promote Staging to Production

on:
  workflow_dispatch:
    inputs:
      confirm_promotion:
        description: 'Type "promote" to confirm promotion of staging to production'
        required: true
        type: string

jobs:
  debug:
    uses: ./.github/workflows/debug-workflow.yml
    with:
      debug_enabled: false

  promote-to-production:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_promotion == 'promote'

    env:
      APP_NAME: ${{ vars.PRODUCTION_APP_NAME }}
      CPLN_ORG: ${{ vars.CPLN_ORG_PRODUCTION }}
      CPLN_TOKEN: ${{ secrets.CPLN_TOKEN_PRODUCTION }}
      UPSTREAM_TOKEN: ${{ secrets.CPLN_TOKEN_STAGING }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          token: ${{ secrets.CPLN_TOKEN_PRODUCTION }}
          org: ${{ vars.CPLN_ORG_PRODUCTION }}

      - name: Promote Staging to Production
        id: promote
        run: |
          echo "🚀 Starting promotion from staging to production... for app ${APP_NAME}"
          
          if ! cpflow promote-app-from-upstream -a "${APP_NAME}" -t "${UPSTREAM_TOKEN}" --org "${CPLN_ORG}"  --verbose --trace   ; then
            echo "❌ Failed to promote staging to production"
            exit 1
          fi
          
          echo "✅ Successfully promoted staging to production"

      - name: Create GitHub Release
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the current date in YYYY-MM-DD format
          RELEASE_DATE=$(date '+%Y-%m-%d')
          
          # Create a release tag
          RELEASE_TAG="production-${RELEASE_DATE}"
          
          # Create GitHub release
          gh release create "${RELEASE_TAG}" \
            --title "Production Release ${RELEASE_DATE}" \
            --notes "🚀 Production deployment on ${RELEASE_DATE}"
